### ISSUE TITLE
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

### ISSUE THREAD

**Issue by fervi** [tangalbert919/nds4droid#14]
Hello. I tried to install your version (ofc. for testing) from ADB (but also normal installation), and I received something like this:
```
fervi@Renzan:~/Pobrane$ adb install app-release.apk 
[100%] /data/local/tmp/app-release.apk
	pkg: /data/local/tmp/app-release.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
```

Fix it if it is posible ;)

**Comment by tangalbert919** [comment]
Are you using version 47.1 from the releases tab or did you compile the entire APK from the source code?

**Comment by fervi** [comment]
From release tab. Version from jesquele works on this phone

**Comment by tangalbert919** [comment]
I will have to re-sign that APK then.
~~Are you using Android Nougat?~~ Don't answer that.
It is recommended that you go through your settings and switch to the normal interpreter if your device is 64-bit. Lightning JIT, the threaded interpreter, and ARM64 do not mix well, and will result in a crash if you don't use the normal interpreter in v47.1.

**Comment by fervi** [comment]
32-bit. (Galaxy Note 2) and OpenGLES2 only. Any ideas? :)

**Comment by fervi** [comment]
OpenGLES maybe doesn't work (it's phone with Replicant 6) [no 3D acceleration, only Software Rendering]

**Comment by tangalbert919** [comment]
The OpenGL ES renderer wasn't really worked on all that much. Some textures render incorrectly as a result.
Does JIT work with v47.1 on your device?

**Comment by fervi** [comment]
Dunno, I can't install it :P

**Comment by tangalbert919** [comment]
Oh. Right. I'll get to that and then edit this post when I'm done.
EDIT: I am done. Try installing the new APK.

**Comment by fervi** [comment]
Works, now some tests (performance etc) - Thanks

**Comment by fervi** [comment]
Works nice, Pokemon are still slow, but I belive in you :P
